#!/usr/bin/env Rscript

###############################################################################
# 07_DrugRepurposing.R
#
# Prepare TWAS-derived gene signatures for CLUE/Connectivity Map analysis and
# summarize drug-repurposing results using the Korean GReX model only.
#
# Computational drug repurposing was performed using the Connectivity Map
# (CMap) approach through the CLUE web platform:
#   https://clue.io/
#
# For each trait, the 50 genes with the strongest positive TWAS associations
# and the 50 genes with the strongest negative TWAS associations were used as
# the up- and down-regulated query signatures, respectively.
#
# Connectivity was evaluated by the CMap connectivity score (tau). Negative
# tau values indicate an inverse relationship between the TWAS-derived trait
# signature and the drug-induced gene-expression signature. Compounds with
# tau <= -90 were considered candidate repurposing drugs.
#
# To prioritize clinically relevant compounds, analyses were restricted to
# FDA-approved drugs using DrugBank version 5.1.12:
#   https://go.drugbank.com/
#
# Drug mechanisms of action were annotated using the CLUE Drug Repurposing Hub.
#
# Workflow:
#   1. Load Korean GReX-based TWAS results generated by 03_run_TWAS.R.
#   2. Rank genes within each trait by signed TWAS Z-score.
#   3. Export the top 50 positive and top 50 negative genes for CLUE.
#   4. Perform CMap analysis on the CLUE web platform.
#   5. Parse downloaded ps_pert_summary.gctx files.
#   6. Retain small-molecule perturbagens (pert_type == "trt_cp").
#   7. Annotate compounds using the CLUE Drug Repurposing Hub.
#   8. Restrict to FDA-approved drugs listed in DrugBank.
#   9. Identify compounds with tau <= -90 and the top-ranked drug per trait.
#
# GTEx-based GReX results are not used in this script.
#
# Usage:
#   Rscript 07_DrugRepurposing.R prepare
#   Rscript 07_DrugRepurposing.R summarize
###############################################################################

suppressPackageStartupMessages({
  library(data.table)
  library(dplyr)
  library(cmapR)
})

# =============================================================================
# 1. Configuration
# =============================================================================

TWAS_DIR <- "/path/to/TWAS_results/Korean"
GENE_ANNOTATION_FILE <- "/path/to/Position_gene.txt"

CLUE_INPUT_DIR <- "/path/to/CLUE/input"
CLUE_RESULTS_DIR <- "/path/to/CLUE/results"

# CLUE Drug Repurposing Hub annotation file.
DRUG_REPURPOSING_HUB_FILE <- "/path/to/DrugRepurposingHub.txt"

# FDA-approved, non-withdrawn drugs from DrugBank version 5.1.12.
DRUGBANK_APPROVED_FILE <- "/path/to/Drugbank_v5.1.12_Approved_notwithdrawn.txt"

OUTPUT_DIR <- "/path/to/DrugRepurposing"

TOP_N <- 50
TAU_THRESHOLD <- -90

# =============================================================================
# 2. Utility functions
# =============================================================================

check_file <- function(path) {
  if (!file.exists(path)) stop("Required file not found: ", path, call. = FALSE)
}

check_dir <- function(path) {
  if (!dir.exists(path)) stop("Required directory not found: ", path, call. = FALSE)
}

load_gene_annotation <- function() {
  check_file(GENE_ANNOTATION_FILE)
  x <- fread(GENE_ANNOTATION_FILE, data.table = FALSE, check.names = FALSE)
  if (!all(c("gene_id", "gene_name") %in% colnames(x))) {
    stop("Gene annotation must contain gene_id and gene_name.", call. = FALSE)
  }
  x %>%
    dplyr::select(gene_id, gene_name) %>%
    dplyr::filter(!is.na(gene_id), !is.na(gene_name), gene_name != "") %>%
    dplyr::distinct(gene_id, .keep_all = TRUE)
}

get_twas_files <- function() {
  check_dir(TWAS_DIR)
  dirs <- c(file.path(TWAS_DIR, "continuous"), file.path(TWAS_DIR, "binary"))
  dirs <- dirs[dir.exists(dirs)]
  files <- unlist(lapply(dirs, function(x) {
    list.files(x, pattern = "\\.tsv$", recursive = TRUE, full.names = TRUE)
  }))
  files <- files[!basename(files) %in% c(
    "TWAS_model_summary.tsv",
    "R2_filtered_GReX_models.tsv"
  )]
  if (length(files) == 0) stop("No Korean TWAS result files found.", call. = FALSE)
  files
}

load_one_twas <- function(file) {
  x <- fread(file, data.table = FALSE, check.names = FALSE)
  required <- c("trait", "gene", "Zscore")
  if (!all(required %in% colnames(x))) {
    stop("TWAS file must contain trait, gene, and Zscore: ", file, call. = FALSE)
  }
  if (length(unique(x$trait)) != 1) {
    stop("Each TWAS file must contain one trait: ", file, call. = FALSE)
  }
  x
}

# =============================================================================
# 3. Prepare CLUE gene signatures
# =============================================================================

prepare_clue_inputs <- function() {
  annot <- load_gene_annotation()
  twas_files <- get_twas_files()
  dir.create(CLUE_INPUT_DIR, recursive = TRUE, showWarnings = FALSE)

  summary_list <- vector("list", length(twas_files))

  for (i in seq_along(twas_files)) {
    x <- load_one_twas(twas_files[i])
    trait <- unique(x$trait)

    x$Gene_name <- annot$gene_name[match(x$gene, annot$gene_id)]
    x <- x[is.finite(x$Zscore), , drop = FALSE]
    x <- x[order(x$Zscore, decreasing = TRUE), , drop = FALSE]

    n_up <- min(TOP_N, nrow(x))
    up <- na.omit(x$Gene_name[seq_len(n_up)])

    down_index <- seq.int(max(1, nrow(x) - TOP_N + 1), nrow(x))
    down <- na.omit(x$Gene_name[rev(down_index)])

    trait_dir <- file.path(CLUE_INPUT_DIR, trait)
    dir.create(trait_dir, recursive = TRUE, showWarnings = FALSE)

    write.table(
      data.frame(Gene = up),
      file = file.path(trait_dir, paste0(trait, "_Top", TOP_N, "_UP_Genes.txt")),
      sep = "\t", col.names = FALSE, row.names = FALSE, quote = FALSE
    )
    write.table(
      data.frame(Gene = down),
      file = file.path(trait_dir, paste0(trait, "_Top", TOP_N, "_DOWN_Genes.txt")),
      sep = "\t", col.names = FALSE, row.names = FALSE, quote = FALSE
    )

    summary_list[[i]] <- data.frame(
      trait = trait,
      n_TWAS_genes = nrow(x),
      n_UP_genes = length(up),
      n_DOWN_genes = length(down),
      stringsAsFactors = FALSE
    )

    message("[", i, "/", length(twas_files), "] ", trait, ": CLUE signature prepared.")
  }

  summary_df <- bind_rows(summary_list)
  fwrite(summary_df, file.path(CLUE_INPUT_DIR, "CLUE_input_summary.tsv"), sep = "\t")
  invisible(summary_df)
}

# =============================================================================
# Web-based CLUE analysis
# =============================================================================
#
# The files generated by prepare_clue_inputs() are submitted manually to:
#
#   https://clue.io/
#
# For each trait:
#   - UP signature:   top 50 genes with the highest signed TWAS Z-scores
#   - DOWN signature: top 50 genes with the lowest signed TWAS Z-scores
#
# CLUE/CMap evaluates connectivity between the TWAS-derived signature and
# perturbagen-induced gene-expression signatures. The resulting connectivity
# score (tau) is downloaded from CLUE.
#
# Expected downloaded result structure:
#
#   CLUE_RESULTS/<TRAIT>/matrices/gutc/ps_pert_summary.gctx
#
# This web-based analysis is not executed by this R script.
#
# =============================================================================
# 4. Parse Korean CLUE results
# =============================================================================

parse_clue_results <- function() {
  check_dir(CLUE_RESULTS_DIR)

  gctx_files <- list.files(
    CLUE_RESULTS_DIR,
    pattern = "^ps_pert_summary\\.gctx$",
    recursive = TRUE,
    full.names = TRUE
  )
  if (length(gctx_files) == 0) stop("No ps_pert_summary.gctx files found.", call. = FALSE)

  result_list <- lapply(gctx_files, function(file) {
    trait <- basename(dirname(dirname(dirname(file))))
    ds <- cmapR::parse_gctx(file)
    x <- as.data.frame(ds@rdesc, stringsAsFactors = FALSE)
    if (ncol(ds@mat) < 1) stop("No tau matrix found in: ", file, call. = FALSE)
    x$Korean_tau <- as.numeric(ds@mat[, 1])
    x$trait <- trait
    x
  })

  result <- bind_rows(result_list) %>%
    dplyr::select(trait, everything())

  dir.create(OUTPUT_DIR, recursive = TRUE, showWarnings = FALSE)
  fwrite(result, file.path(OUTPUT_DIR, "CLUE_Korean_all_results.tsv"), sep = "\t")
  result
}

# =============================================================================
# 5. Drug annotation and filtering
# =============================================================================

load_drug_resources <- function() {
  check_file(DRUG_REPURPOSING_HUB_FILE)
  check_file(DRUGBANK_APPROVED_FILE)

  hub <- fread(DRUG_REPURPOSING_HUB_FILE, data.table = FALSE, check.names = FALSE)
  if (!all(c("pert_iname", "moa", "indication") %in% colnames(hub))) {
    stop("Drug Repurposing Hub file must contain pert_iname, moa, and indication.", call. = FALSE)
  }

  drugbank <- fread(DRUGBANK_APPROVED_FILE, data.table = FALSE, check.names = FALSE)
  if (!"name" %in% colnames(drugbank)) {
    stop("DrugBank file must contain name.", call. = FALSE)
  }

  hub$drug_key <- tolower(trimws(as.character(hub$pert_iname)))
  drugbank$drug_key <- tolower(trimws(as.character(drugbank$name)))

  list(
    hub = hub,
    approved_keys = unique(drugbank$drug_key)
  )
}

summarize_drug_repurposing <- function() {
  clue <- parse_clue_results()
  resources <- load_drug_resources()

  required <- c("pert_type", "pert_iname", "Korean_tau", "trait")
  if (!all(required %in% colnames(clue))) {
    stop("CLUE result must contain: ", paste(required, collapse = ", "), call. = FALSE)
  }

  compounds <- clue %>%
    dplyr::filter(pert_type == "trt_cp") %>%
    dplyr::mutate(drug_key = tolower(trimws(as.character(pert_iname))))

  hub <- resources$hub %>%
    dplyr::select(drug_key, pert_iname, moa, indication) %>%
    dplyr::distinct(drug_key, .keep_all = TRUE) %>%
    dplyr::rename(
      hub_pert_iname = pert_iname,
      mechanism_of_action = moa
    )

  annotated <- compounds %>%
    dplyr::left_join(hub, by = "drug_key")

  in_hub <- annotated %>%
    dplyr::filter(!is.na(hub_pert_iname))

  approved <- in_hub %>%
    dplyr::filter(drug_key %in% resources$approved_keys)

  significant <- approved %>%
    dplyr::filter(Korean_tau <= TAU_THRESHOLD) %>%
    dplyr::arrange(trait, Korean_tau)

  top1 <- approved %>%
    dplyr::group_by(trait) %>%
    dplyr::slice_min(order_by = Korean_tau, n = 1, with_ties = FALSE) %>%
    dplyr::ungroup() %>%
    dplyr::mutate(significant = Korean_tau <= TAU_THRESHOLD) %>%
    dplyr::arrange(trait)

  dir.create(OUTPUT_DIR, recursive = TRUE, showWarnings = FALSE)

  fwrite(
    in_hub,
    file.path(OUTPUT_DIR, "CLUE_Korean_DrugRepurposingHub_compounds.tsv"),
    sep = "\t"
  )
  fwrite(
    approved,
    file.path(OUTPUT_DIR, "CLUE_Korean_approved_compounds.tsv"),
    sep = "\t"
  )
  fwrite(
    significant,
    file.path(OUTPUT_DIR, "CLUE_Korean_significant_tau_le_minus90.tsv"),
    sep = "\t"
  )
  fwrite(
    top1,
    file.path(OUTPUT_DIR, "CLUE_Korean_top1_per_trait.tsv"),
    sep = "\t"
  )

  message(
    "Approved compounds: ", nrow(approved),
    "; tau <= ", TAU_THRESHOLD, ": ", nrow(significant),
    "; traits with top-ranked candidates: ", dplyr::n_distinct(top1$trait)
  )

  invisible(list(
    all_clue = clue,
    approved = approved,
    significant = significant,
    top1 = top1
  ))
}

# =============================================================================
# 6. Command-line interface
# =============================================================================

args <- commandArgs(trailingOnly = TRUE)
mode <- if (length(args) == 0) "prepare" else tolower(args[1])

if (mode == "prepare") {
  prepare_clue_inputs()
} else if (mode == "summarize") {
  summarize_drug_repurposing()
} else {
  stop("Usage: Rscript 07_DrugRepurposing.R [prepare|summarize]", call. = FALSE)
}
