#!/usr/bin/env Rscript

###############################################################################
# 06_prepare_GSEA.R
#
# Prepare ranked gene lists (.rnk) for gene set enrichment analysis (GSEA)
# using Korean GReX-based TWAS results.
#
# GSEA was performed separately for each trait using WebGestalt:
#   https://www.webgestalt.org/
#
# All genes with valid TWAS association statistics were ranked according to
# the signed TWAS Z-score generated in 03_run_TWAS.R.
#
# The following WebGestalt functional databases were used:
#
#   1. community-contributed / Hallmark50
#   2. pathway / KEGG
#   3. pathway / Reactome
#   4. geneontology / Biological Process noRedundant
#
# WebGestalt analysis settings used in the study:
#   - GSEA method
#   - ranked input: gene symbol + signed TWAS Z-score
#   - minimum gene-set size: 10
#   - maximum gene-set size: 500
#   - number of permutations: 1,000
#   - significance threshold: FDR < 0.05
#   - enrichment was evaluated separately for each trait and gene-set
#     collection
#
# Manuscript Methods:
#
# "Gene set enrichment analysis was performed separately for each trait using
# WebGestalt. All genes with valid TWAS association statistics were ranked
# according to the signed TWAS Z-score. Enrichment was evaluated against the
# MSigDB Hallmark, Kyoto Encyclopedia of Genes and Genomes (KEGG), Gene
# Ontology Biological Process (GO BP), and Reactome gene-set collections.
# Gene sets represented by 10-500 genes in the ranked input list were retained
# for analysis. Enrichment significance and normalized enrichment scores were
# estimated using 1,000 permutations, and gene sets with a false discovery
# rate (FDR) of less than 0.05 within each trait and gene-set collection were
# considered significant."
#
# This script only prepares the ranked input files. WebGestalt enrichment is
# subsequently performed through the WebGestalt web interface using the above
# settings.
#
# Usage:
#   Rscript 06_prepare_GSEA.R
###############################################################################

suppressPackageStartupMessages({
  library(data.table)
  library(dplyr)
})

# =============================================================================
# 1. Configuration
# =============================================================================

# Korean-based TWAS results generated by 03_run_TWAS.R.
TWAS_DIR <- "/path/to/TWAS_results/Korean"

# Gene annotation containing at least:
#   gene_id, gene_name
GENE_ANNOTATION_FILE <- "/path/to/Position_gene.txt"

OUTPUT_DIR <- "/path/to/GSEA/rnk"

# =============================================================================
# 2. Utility functions
# =============================================================================

check_file <- function(path) {
  if (!file.exists(path)) stop("Required file not found: ", path, call. = FALSE)
}

check_dir <- function(path) {
  if (!dir.exists(path)) stop("Required directory not found: ", path, call. = FALSE)
}

load_gene_annotation <- function() {
  check_file(GENE_ANNOTATION_FILE)
  annot <- fread(GENE_ANNOTATION_FILE, data.table = FALSE, check.names = FALSE)

  if (!all(c("gene_id", "gene_name") %in% colnames(annot))) {
    stop(
      "Gene annotation must contain gene_id and gene_name.",
      call. = FALSE
    )
  }

  annot <- annot %>%
    dplyr::select(gene_id, gene_name) %>%
    dplyr::filter(
      !is.na(gene_id),
      !is.na(gene_name),
      gene_name != ""
    ) %>%
    dplyr::distinct(gene_id, .keep_all = TRUE)

  annot
}

# =============================================================================
# 3. Locate Korean TWAS result files
# =============================================================================

get_twas_files <- function() {
  check_dir(TWAS_DIR)

  result_dirs <- c(
    file.path(TWAS_DIR, "continuous"),
    file.path(TWAS_DIR, "binary")
  )

  result_dirs <- result_dirs[dir.exists(result_dirs)]

  files <- unlist(
    lapply(
      result_dirs,
      function(x) {
        list.files(
          x,
          pattern = "\\.tsv$",
          recursive = TRUE,
          full.names = TRUE
        )
      }
    )
  )

  # Exclude model-level metadata files if present.
  files <- files[
    !basename(files) %in% c(
      "TWAS_model_summary.tsv",
      "R2_filtered_GReX_models.tsv"
    )
  ]

  if (length(files) == 0) {
    stop(
      "No Korean TWAS result files found under: ",
      TWAS_DIR,
      call. = FALSE
    )
  }

  files
}

# =============================================================================
# 4. Prepare one ranked gene list
# =============================================================================

prepare_ranked_list <- function(twas_file, gene_annotation) {
  x <- fread(
    twas_file,
    data.table = FALSE,
    check.names = FALSE
  )

  required <- c(
    "trait",
    "gene",
    "Zscore"
  )

  if (!all(required %in% colnames(x))) {
    stop(
      "TWAS file is missing required columns: ",
      twas_file,
      call. = FALSE
    )
  }

  traits <- unique(x$trait)

  if (length(traits) != 1) {
    stop(
      "Each TWAS result file must contain exactly one trait: ",
      twas_file,
      call. = FALSE
    )
  }

  trait <- traits[1]

  x <- x %>%
    dplyr::mutate(
      Gene_name = gene_annotation$gene_name[
        match(gene, gene_annotation$gene_id)
      ]
    ) %>%
    dplyr::filter(
      is.finite(Zscore),
      !is.na(Gene_name),
      Gene_name != ""
    ) %>%
    dplyr::arrange(desc(Zscore)) %>%
    dplyr::select(
      Gene_name,
      Zscore
    )

  if (nrow(x) == 0) {
    warning(
      "No valid genes for trait: ",
      trait
    )
    return(NULL)
  }

  duplicated_symbols <- unique(
    x$Gene_name[duplicated(x$Gene_name)]
  )

  if (length(duplicated_symbols) > 0) {
    warning(
      trait,
      ": duplicated gene symbols are present in the ranked list (n = ",
      length(duplicated_symbols),
      "). They are retained to reproduce the original preparation procedure."
    )
  }

  list(
    trait = trait,
    ranked = x
  )
}

# =============================================================================
# 5. Generate WebGestalt .rnk files
# =============================================================================

dir.create(
  OUTPUT_DIR,
  recursive = TRUE,
  showWarnings = FALSE
)

gene_annotation <- load_gene_annotation()
twas_files <- get_twas_files()

summary_list <- vector(
  "list",
  length(twas_files)
)

for (i in seq_along(twas_files)) {
  result <- prepare_ranked_list(
    twas_files[i],
    gene_annotation
  )

  if (is.null(result)) next

  trait <- result$trait
  ranked <- result$ranked

  output_file <- file.path(
    OUTPUT_DIR,
    paste0(
      trait,
      ".rnk"
    )
  )

  write.table(
    ranked,
    file = output_file,
    sep = "\t",
    col.names = FALSE,
    row.names = FALSE,
    quote = FALSE
  )

  summary_list[[i]] <- data.frame(
    trait = trait,
    n_ranked_genes = nrow(ranked),
    rnk_file = output_file,
    stringsAsFactors = FALSE
  )

  message(
    "[",
    i,
    "/",
    length(twas_files),
    "] ",
    trait,
    ": ",
    nrow(ranked),
    " genes"
  )
}

summary_df <- bind_rows(summary_list)

fwrite(
  summary_df,
  file.path(
    OUTPUT_DIR,
    "GSEA_ranked_file_summary.tsv"
  ),
  sep = "\t"
)

message(
  "Prepared ",
  nrow(summary_df),
  " trait-specific ranked files for WebGestalt."
)
